version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "rails"

      # tailwind v4とkamalでデプロイ先にCSSが反映されない不具合があるため、v4を一時的に除外
      - dependency-name: "tailwindcss-ruby"
        versions: ["~> 4.0"]
      - dependency-name: "tailwindcss-rails"
        versions: ["~> 4.0"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
